name: NegativeStain
atlas:
  steps:
      - setAtlasOptics
      - resetStage
      - removeSlit
      - atlas
  targets:
    finders:
      - AI square finder
    selectors:
      - Size selector
square:
  steps:
    - setSquareMagOptics
    - moveStageWithAtlasToSearchOffset
    - realignToSquare
    - eucentricMediumMag
    - square
  targets:
    finders:
      - Regular pattern
    selectors:
      - Graylevel selector
      - Distance from center selector
mediumMag:
  steps:
    - setMediumMagOptics
    - tiltToAngle
    - moveStage
    - zeroImageShift
    - mediumMagHole
    - setHighMagOptics
    - rollDefocus
    - autoFocus
    - waitDrift
    - setAFISimageShift
highMag:
  steps:
    - highMag
