name: NegativeStain
atlas:
  steps:
      - setAtlasOptics
      - setAperturesForLowMag
      - resetStage
      - removeSlit
      - atlas
  targets:
    finders:
      - AI square finder
    selectors:
      - Size selector
square:
  steps:
    - setAperturesForLowMag
    - moveStageWithAtlasToSearchOffset
    - realignToSquare
    - eucentricSearch
    - square
  targets:
    finders:
      - Regular pattern
    selectors:
      - Graylevel selector
      - Distance from center selector
mediumMag:
  steps:
    - setAperturesForHighMag
    - tiltToAngle
    - moveStage
    - mediumMagHole
    - rollDefocus
    - autoFocus
    - waitDrift
highMag:
  steps:
    - highMag
