name: SPA MM-lattice Finder 
atlas:
  steps:
      - setAtlasOptics
      - resetStage
      - removeSlit
      - atlas
  targets:
    finders:
      - AI square finder
    selectors:
      - Size selector
square:
  steps:
    - setSquareMagOptics
    - moveStageWithAtlasToSearchOffset
    - realignToSquare
    - eucentricSearchAfterDistance:
        distance: 300
    - square
  targets:
    finders:
      - AI hole finder
      - Regular pattern
    selectors:
      - Graylevel selector
      - Distance from center selector
mediumMag:
  steps:
    - setFocusPosition
    - setHighMagOptics
    - rollDefocus
    - refineEucentricityByFocus
    - tiltToAngle
    - moveStage
    - zeroImageShift
    - mediumMagHole
    - setHighMagOptics
    - autoFocusAfterDistance:
        distance: 15
    - waitDrift
    - setAFISimageShift
  targets:
    finders:
      - MM AI hole finder with lattice
highMag:
  steps:
    - highMag
