name: SPA-hex
atlas:
  steps:
      - setAtlasOptics
      - setAperturesForLowMag
      - resetStage
      - removeSlit
      - atlas
  targets:
    finders:
      - AI square finder
    selectors:
      - Size selector
square:
  steps:
    - setAperturesForLowMag
    - setSquareMagOptics
    - moveStageWithAtlasToSearchOffset
    - realignToSquare
    - eucentricSearch
    - square
  targets:
    finders:
      - Binary Finder
      # - AI hole finder
    selectors:
      - Graylevel selector
      - Distance from center selector
mediumMag:
  steps:
    - setAperturesForHighMag
    - setFocusPosition
    - setHighMag
    - rollDefocus
    - refineEucentricityByFocus
    - tiltToAngle
    - moveStage
    - zeroImageShift
    - mediumMagHole
    - setHighMagOptics
    - autoFocusAfterDistance:
        distance: 15
    - waitDrift
    - setAFISimageShift
  targets:
    finders:
      - Medium Mag AI hole finder
highMag:
  steps:
    - highMag
