name: SPA MM Finder Precise
# preImaging:
#   steps:
#     - setHighmagCountingMode
#     - loadGrid
#     - setupFrames
#     - openColumnValve
#     - resetState
atlas:
  acquisition:
      - setAtlasOptics
      - setAperturesForLowMag
      - resetStage
      - removeSlit
      - atlas
  targets:
    finders:
      - AI square finder
    selectors:
      - Size selector
square:
  acquisition:
    - setAperturesForLowMag
    - moveStageWithAtlasToSearchOffset
    - realignToSquare
    - eucentricMediumMag
    - square
  targets:
    finders:
      - AI hole finder
      - Regular pattern
    selectors:
      - Graylevel selector
      - Distance from center selector
mediumMag:
  acquisition:
    - setAperturesForHighMag
    - setFocusPosition
    - tiltToAngle
    - moveStage
    - createHoleRef
    - alignToHoleRef
    - zeroImageShift
    - mediumMagHole
    - rollDefocus
    - autoFocus
    - waitDrift
  targets:
    finders:
      - Medium Mag AI hole finder
highMag:
  acquisition:
    - highMag
# postHighMag:
#   steps:
#     - resetAFISimageShift
#     - refineZLP
#     - collectHardwareDark
#     - flashColdFEG
#     - recenterBeam

