name: SPA MM Finder Precise
atlas:
  steps:
      - setAtlasOptics
      - resetStage
      - removeSlit
      - atlas
  targets:
    finders:
      - AI square finder
    selectors:
      - Size selector
square:
  steps:
    - setSquareMagOptics
    - moveStageWithAtlasToSearchOffset
    - realignToSquare
    - eucentricMediumMag
    - square
  targets:
    finders:
      - AI hole finder
      - Regular pattern
    selectors:
      - Graylevel selector
      - Distance from center selector
mediumMag:
  steps:
    - setMediumMagOptics
    - setFocusPosition
    - tiltToAngle
    - moveStage
    - createHoleRef
    - alignToHoleRef
    - zeroImageShift
    - mediumMagHole
    - setHighMagOptics
    - rollDefocus
    - autoFocus
    - waitDrift
    - setAFISimageShift
  targets:
    finders:
      - Medium Mag AI hole finder
highMag:
  steps:
    - highMag
# postHighMag:
#   steps:
#     - resetAFISimageShift
#     - refineZLP
#     - collectHardwareDark
#     - flashColdFEG
#     - recenterBeam

