# Generated by Django 4.2.2 on 2024-11-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0024_detector_deprecated'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningsession',
            name='creation_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='screeningsession',
            name='session',
            field=models.CharField(max_length=60),
        ),
    ]
