# Generated by Django 4.2.2 on 2024-11-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_screeningsession_creation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoloadergrid',
            name='collection_mode',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
