# Generated by Django 4.2.2 on 2025-02-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0026_autoloadergrid_collection_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screeningsession',
            options={'ordering': ['-creation_time']},
        ),
        migrations.AddField(
            model_name='gridcollectionparams',
            name='max_exposures_for_grid',
            field=models.IntegerField(default=-1, help_text='Move on to the next grid when this number of exposures were acquired.', verbose_name='Max Exposures For Grid'),
        ),
    ]
