# Generated by Django 4.2.2 on 2025-02-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0027_alter_screeningsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microscope',
            name='temperature_control',
            field=models.BooleanField(default=True, help_text='Check if you have a scope with automated dewar refills.'),
        ),
        migrations.AlterField(
            model_name='microscope',
            name='aperture_control',
            field=models.BooleanField(default=False, help_text='Check box if serialEM is able to control the aperture selection. Check only if you have JEOL CRYOARM, or a TFS with automated apertures.'),
        ),
    ]
