# Generated by Django 5.2 on 2025-07-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0028_microscope_temperature_control_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highmagmodel',
            name='selection_mode',
            field=models.CharField(choices=[('manual', 'User selected'), ('automated', 'Automated selection')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='holemodel',
            name='selection_mode',
            field=models.CharField(choices=[('manual', 'User selected'), ('automated', 'Automated selection')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='squaremodel',
            name='selection_mode',
            field=models.CharField(choices=[('manual', 'User selected'), ('automated', 'Automated selection')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='autoloadergrid',
            name='collection_mode',
            field=models.CharField(choices=[('collection', 'Collection'), ('screening', 'Screening')], default=None, max_length=30, null=True),
        ),
    ]
