# Generated by Django 5.2 on 2025-07-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0029_highmagmodel_selection_mode_holemodel_selection_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highmagmodel',
            name='acquisition_priority',
            field=models.IntegerField(default=0, help_text='Priority for acquisition, lower number means higher priority.'),
        ),
        migrations.AddField(
            model_name='holemodel',
            name='acquisition_priority',
            field=models.IntegerField(default=0, help_text='Priority for acquisition, lower number means higher priority.'),
        ),
        migrations.AddField(
            model_name='squaremodel',
            name='acquisition_priority',
            field=models.IntegerField(default=0, help_text='Priority for acquisition, lower number means higher priority.'),
        ),
    ]
