# Generated by Django 5.2 on 2025-09-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0030_highmagmodel_acquisition_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoloadergrid',
            name='loading_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='autoloadergrid',
            name='unloading_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
