# Generated by Django 5.2 on 2026-01-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0031_autoloadergrid_loading_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlasmodel',
            name='curated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='highmagmodel',
            name='curated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holemodel',
            name='curated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squaremodel',
            name='curated',
            field=models.BooleanField(default=False),
        ),
    ]
