# Generated by Django 5.2 on 2026-03-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0032_atlasmodel_curated_highmagmodel_curated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='squaremodel',
            name='eucentricity_refined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gridcollectionparams',
            name='highmag_aperture_size',
            field=models.IntegerField(default=50, help_text='Size of the aperture for the View and Record presets. C2 aperture size for Thermo microscopes. CL for JEOL.', verbose_name='High Mag Aperture Size'),
        ),
    ]
