# Generated by Django 5.2 on 2026-07-17 01:29

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0033_squaremodel_eucentricity_refined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microscope',
            name='narrow_gap_polepiece',
            field=models.BooleanField(default=False, help_text='Check if the microscope has a narrow gap polepiece to enable disable tilting. Only works on CRYOARM at the moment.'),
        ),
        migrations.CreateModel(
            name='FiducialArea',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('pixel_size', models.FloatField(null=True)),
                ('shape_x', models.IntegerField(null=True)),
                ('shape_y', models.IntegerField(null=True)),
                ('selected', models.BooleanField(default=False)),
                ('curated', models.BooleanField(default=False)),
                ('selection_mode', models.CharField(choices=[('manual', 'User selected'), ('automated', 'Automated selection')], max_length=20, null=True)),
                ('acquisition_priority', models.IntegerField(default=0, help_text='Priority for acquisition, lower number means higher priority.')),
                ('status', models.CharField(default=None, max_length=20, null=True)),
                ('completion_time', models.DateTimeField(null=True)),
                ('fiducial_area_id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('area_type', models.CharField(blank=True, max_length=100, null=True)),
                ('grid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.autoloadergrid')),
            ],
            options={
                'db_table': 'fiducialarea',
                'abstract': False,
            },
            managers=[
                ('display', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FocusPosition',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('pixel_size', models.FloatField(null=True)),
                ('shape_x', models.IntegerField(null=True)),
                ('shape_y', models.IntegerField(null=True)),
                ('selected', models.BooleanField(default=False)),
                ('curated', models.BooleanField(default=False)),
                ('selection_mode', models.CharField(choices=[('manual', 'User selected'), ('automated', 'Automated selection')], max_length=20, null=True)),
                ('acquisition_priority', models.IntegerField(default=0, help_text='Priority for acquisition, lower number means higher priority.')),
                ('status', models.CharField(default=None, max_length=20, null=True)),
                ('completion_time', models.DateTimeField(null=True)),
                ('focus_position_id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('grid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.autoloadergrid')),
            ],
            options={
                'db_table': 'focusposition',
                'abstract': False,
            },
            managers=[
                ('display', django.db.models.manager.Manager()),
            ],
        ),
    ]
