# Generated by Django 5.2 on 2026-09-05 01:48

from django.db import migrations, models


def deduplicate_grid_collection_params(apps, schema_editor):
    """Repoint grids sharing identical params to a single row and delete the duplicates.

    Concurrent get_or_create calls could insert duplicate rows (no unique
    constraint existed), eventually causing MultipleObjectsReturned on lookups.
    """
    GridCollectionParams = apps.get_model('API', 'GridCollectionParams')
    AutoloaderGrid = apps.get_model('API', 'AutoloaderGrid')

    fields = [f.name for f in GridCollectionParams._meta.concrete_fields if f.name != 'params_id']
    seen = {}
    for params in GridCollectionParams.objects.all().order_by('params_id'):
        key = tuple(getattr(params, f) for f in fields)
        if key in seen:
            AutoloaderGrid.objects.filter(params_id=params.pk).update(params_id=seen[key])
            params.delete()
        else:
            seen[key] = params.pk


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0034_microscope_narrow_gap_polepiece_fiducialarea_and_more'),
    ]

    operations = [
        migrations.RunPython(deduplicate_grid_collection_params, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='gridcollectionparams',
            constraint=models.UniqueConstraint(fields=('atlas_x', 'atlas_y', 'square_x', 'square_y', 'squares_num', 'holes_per_square', 'max_exposures_for_grid', 'bis_max_distance', 'min_bis_group_size', 'afis', 'target_defocus_min', 'target_defocus_max', 'step_defocus', 'drift_crit', 'tilt_angle', 'save_frames', 'force_process_from_average', 'highmag_aperture_size', 'objective_aperture_size', 'offset_targeting', 'offset_distance', 'zeroloss_delay', 'hardwaredark_delay', 'coldfegflash_delay', 'beam_centering_delay', 'multishot_per_hole'), name='unique_gridcollectionparams'),
        ),
    ]
