# Generated by Django 5.2 on 2026-07-31 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0034_microscope_narrow_gap_polepiece_fiducialarea_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classifier',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='finder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='selector',
            options={'ordering': ['-created_at']},
        ),
    ]
