FROM ubuntu:24.04

LABEL org.opencontainers.image.source=https://github.com/NIEHS/SmartScope
LABEL org.opencontainers.image.title=SmartScope
LABEL org.opencontainers.image.description="SmartScope is a framework for automated cryo-electron microscopy"
LABEL org.opencontainers.image.licenses=BSD-3-Clause

ARG VERSION='0.8-rc.2'
ARG BRANCH='stable'

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
	python3-dev default-libmysqlclient-dev build-essential wget libglib2.0-0 ffmpeg libsm6 libxext6 curl mariadb-server git pkg-config && \
	apt-get clean && rm -rf /var/cache/apt/lists

# Download the latest installer, install it and then remove it
ADD https://astral.sh/uv/install.sh /install.sh
RUN chmod -R 655 /install.sh && /install.sh && rm /install.sh

COPY --link IMOD /usr/local/IMOD

ENV IMOD_DIR=/usr/local/IMOD
ENV PATH=/root/.local/bin:$PATH:/opt/miniforge3/bin:/usr/local/IMOD/bin
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/IMOD/lib


#General environment variables
ENV VERSION=$VERSION \
	IMOD_DIR=/usr/local/IMOD \	
	CTFFIND=/opt/ctffind \
	APP=/opt/smartscope/ \
	AUTOSCREENDIR=/mnt/data/ \
	TEMPDIR=/tmp/ \
	LOGDIR=/opt/logs/ \
	AUTOSCREENSTORAGE=/mnt/longterm/
	# TEMPLATE_FILES=/opt/Template_files/

ENV	ALLOWED_HOSTS=localhost \
	CONFIG=/opt/config/ \
	USE_SSL=false \
	EXTERNAL_PLUGINS_DIRECTORY=/opt/external_plugins/ \
	AUTO_MIGRATION=true \
	DJANGO_SETTINGS_MODULE=Smartscope.core.settings.server_docker \
	USE_STORAGE=True \
	USE_LONGTERMSTORAGE=False \
	USE_MICROSCOPE=True \ 
	DEFAULT_UMASK=002 \
	LOGLEVEL=INFO \
	DEBUG=False \
	DEPLOY=True \
	TEST_FILES=/mnt/testfiles/ \
	MYSQL_HOST=db \
	MYSQL_PORT=3306 \
	MYSQL_USERNAME=root \
	MYSQL_PASSWORD=pass \ 
	DB_NAME=smartscope \
	REDIS_HOST=cache \
	REDIS_PORT=6379 \
	USE_AWS=False \
	FORCE_CPU=False

# ENV PATH=$PATH:/opt/smartscope/Smartscope/bin

# COPY --link Template_files/ /opt/Template_files/
COPY --link ctffind /opt/
# COPY --link miniforge3/ /opt/miniforge3/
COPY smartscope/ /opt/smartscope/
COPY external_plugins/ /opt/external_plugins/
COPY Smartscope-connector /opt/Smartscope-connector/


# RUN wget docs.smartscope.org/downloads/Smartscope0.6.tar.gz --no-check-certificate && \
# 	tar -xvf Smartscope0.6.tar.gz -C /opt/ && \
# 	rm Smartscope0.6.tar.gz

RUN	mkdir /opt/logs/ /mnt/fake_scope/ /mnt/fake_scope/raw/ /mnt/fake_scope/movies/ /opt/shared/ /opt/config/ /mnt/testfiles
# RUN pip install -e /opt/smartscope/ --no-dependencies && \
# 	pip install -e /opt/smartscope/SerialEM-python --no-dependencies

RUN chmod 777 -R /mnt/ && \
	chmod 777 -R /opt/logs/ && \
	chmod 777 /opt/shared/ && \
	chmod 777 /opt/config/ && \
	chmod -R 777 /opt/Template_files
	# chmod 777 /mnt/testfiles/

ARG USER_ID=9999

RUN	useradd -m --no-log-init --system  --uid $USER_ID smartscope_user

USER smartscope_user

WORKDIR /opt/smartscope/

#General environment variables
ENV VERSION=$VERSION \
	IMOD_DIR=/usr/local/IMOD \	
	CTFFIND=/opt/ctffind \
	APP=/opt/smartscope/ \
	AUTOSCREENDIR=/mnt/data/ \
	TEMPDIR=/tmp/ \
	LOGDIR=/opt/logs/ \
	AUTOSCREENSTORAGE=/mnt/longterm/
	# TEMPLATE_FILES=/opt/Template_files/

ENV	ALLOWED_HOSTS=localhost \
	CONFIG=/opt/config/ \
	USE_SSL=false \
	EXTERNAL_PLUGINS_DIRECTORY=/opt/external_plugins/ \
	AUTO_MIGRATION=true \
	DJANGO_SETTINGS_MODULE=Smartscope.core.settings.server_docker \
	USE_STORAGE=True \
	USE_LONGTERMSTORAGE=False \
	USE_MICROSCOPE=True \ 
	DEFAULT_UMASK=002 \
	LOGLEVEL=INFO \
	DEBUG=False \
	DEPLOY=True \
	TEST_FILES=/mnt/testfiles/ \
	MYSQL_HOST=db \
	MYSQL_PORT=3306 \
	MYSQL_USERNAME=root \
	MYSQL_PASSWORD=pass \ 
	DB_NAME=smartscope \
	REDIS_HOST=cache \
	REDIS_PORT=6379 \
	USE_AWS=False \
	FORCE_CPU=False

ENV PATH="/app/.venv/bin:$PATH"

ENTRYPOINT [ "/opt/smartscope/Docker/entrypoint.sh" ]

CMD [ "uv", """gunicorn", "-c", "/opt/smartscope/config/docker/gunicorn.conf.py" ]