FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
	python3-dev default-libmysqlclient-dev build-essential wget libglib2.0-0 ffmpeg libsm6 libxext6 curl mariadb-server git pkg-config && \
	apt-get clean && rm -rf /var/cache/apt/lists

# RUN wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
# 	bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda3 && \
# 	rm Miniconda3-latest-Linux-x86_64.sh

COPY --link IMOD /usr/local/IMOD

ENV IMOD_DIR=/usr/local/IMOD
ENV PATH=$PATH:/opt/miniforge3/bin:/usr/local/IMOD/bin
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/IMOD/lib

# RUN conda update -y conda && \
# 	yes | conda install python=3.9 && \
# 	yes | conda install cudatoolkit=11.1 cudnn -c nvidia \
# 	yes | conda install pytorch torchvision -c pytorch-lts -c nvidia && \
# 	conda clean --all

# ADD config/docker/requirements.txt .

# RUN	yes | pip install numpy==1.21.0 && \
# 	# yes | pip install torch==1.8.2 torchvision==0.9.2 torchaudio==0.8.2 --extra-index-url https://download.pytorch.org/whl/lts/1.8/cu111 && \
# 	yes | pip install -r requirements.txt && \
# 	pip cache purge
	

# create a non-root user
ARG USER_ID=9999

RUN	useradd -m --no-log-init --system  --uid $USER_ID smartscope_user