# Generated by Django 5.2 on 2025-06-12 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('API', '0028_microscope_temperature_control_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimSiamWeights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the SimSiam model.', max_length=255)),
                ('mag_level', models.CharField(choices=[('hole', 'Square'), ('square', 'Atlas')], help_text='Magnification level of the model.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the model was created.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Date and time when the model was last updated.')),
                ('last_used', models.DateTimeField(blank=True, help_text='Date and time when the model was last used.', null=True)),
                ('grid_id', models.ForeignKey(blank=True, help_text='Grid ID associated with the model.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_siam_models', to='API.autoloadergrid')),
                ('project_tag', models.ForeignKey(blank=True, help_text='Project tag associated with the model.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.projecttag')),
                ('sample_tag', models.ForeignKey(blank=True, help_text='Sample tag associated with the model.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.sampletag')),
            ],
        ),
        migrations.CreateModel(
            name='SimSiamTrainingProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(help_text='Name of the dataset used for training.', max_length=255)),
                ('training_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the training was performed.')),
                ('process_id', models.CharField(blank=True, help_text='Unique identifier for the training process.', max_length=255, null=True)),
                ('training_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the training process.', max_length=50)),
                ('sim_siam_weights', models.ForeignKey(blank=True, help_text='Weights associated with the training process.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_processes', to='sim_siam.simsiamweights')),
            ],
        ),
    ]
