# Generated by Django 5.2 on 2025-06-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_siam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simsiamtrainingprocess',
            name='message',
            field=models.TextField(blank=True, help_text='Message or log related to the training process.', null=True),
        ),
    ]
